### PR TITLE
206 make initial hallway connections to rooms

### LINKED ISSUE #206: Make initial hallway connections to rooms
Hallways currently do not create gaps in the walls of rooms. We need to identify the locations where hallways connect to rooms and replace the wall with an appropriate tile. This can be a placeholder for the purpose of this issue.

### PR DESCRIPTION
**Pull request by Twetny**
Closes #206

### CODE REVIEW

**Comment by Naomi-Parte** [comment]
I can see a couple of edge cases like these:
image

and also in some cases, it looks like the tile IDs are not updated along with the tile displays like here:
image

Are these expected in this PR or will they be fixed?

**Comment by Naomi-Parte** [comment]
Looks super cool with a big dungeon tho!
image

**Comment by Twetny** [comment]
> I can see a couple of edge cases like these: image
> 
> and also in some cases, it looks like the tile IDs are not updated along with the tile displays like here: image
> 
> Are these expected in this PR or will they be fixed?

The first edge case is expected in this PR and is not being fixed here.

Could you also explain more about the 2nd image, I'm not too familiar with what's going on there as that looks fine.

**Comment by Naomi-Parte** [comment]
ah I see. Will the edge case ever be fixed in the future or are we happy with it?

For the second image, some props have a rule that makes them generate on walls. The logic for this uses the tile ID/ tile spacial ID as the tiles know if they are floor or walls etc based on their ID property. But there are multiple cases like that image which means the original wall edge tile that has been turned into a normal floor tile doesn't know it is a floor tile in it's tile ID/ tile spacial ID. I don't know if that makes sense?

**Comment by Twetny** [comment]
> ah I see. Will the edge case ever be fixed in the future or are we happy with it?
> 
> For the second image, some props have a rule that makes them generate on walls. The logic for this uses the tile ID/ tile spacial ID as the tiles know if they are floor or walls etc based on their ID property. But there are multiple cases like that image which means the original wall edge tile that has been turned into a normal floor tile doesn't know it is a floor tile in it's tile ID/ tile spacial ID. I don't know if that makes sense?

As of right now, it's likely how it is going to be. It's not ideal but that specific case is a bit complex to handle and was not a priority relative to the other issues we had.

That does make sense, that might be something to talk to @AboodAsfari about. It also might be the order in which we do things such that we generate the hallways after the props have been generated. I'm not too familiar with that part, unfortunately.

**Comment by Naomi-Parte** [comment]
I see. Okay I think it might be the latter case but I can approve this branch for now. Is it published on npm?

**Review by Naomi-Parte — APPROVED** [review]
ready to merge :)

**Pull request merged**
