### PR TITLE
188 enhance visuals of prop viewer

### PR DESCRIPTION
**Pull request by AboodAsfari**
I've added a prop view on hover, and made the design of the dialog on click match up with the rest of the design of the site. Can also click on an item inside a prop to see more information about it. Let me know if you think anything should change with the way it currently is!

### CODE REVIEW

**Review by dbatoon — CHANGES_REQUESTED** [review]
Each item inside a prop displays the prop's description instead of the item's actual description from `item_metadata.json`. Would be good to have this fixed.

image

image

**Review by dbatoon — APPROVED** [review]
LGTM

**Comment by Naomi-Parte** [comment]
Not sure if it is supposed to look like this since I saw other images of the container being the same height.

image

**Comment by AboodAsfari** [comment]
> Not sure if it is supposed to look like this since I saw other images of the container being the same height.
> 
> image

Yep, was talking with Diana about it and the item panel needed more space for the properties (which don't appear in that screenshot? hmm), but extra height looks off for the prop itself. Thought this looked okay but if it looks off let me know and we can find a better solution :)

**Review by Naomi-Parte — APPROVED** [review]
Looks good.

**Pull request merged**
